inherit_from: .rubocop_todo.yml
Cops:
  Exclude:
    - db/schema.rb
    - app/assests/javascripts/bootstrap.js
StringLiterals:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Tab:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundBody:
  Enabled: false
Style/EmptyLinesAroundMethodDefinition:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/FinalNewline:
  Enabled: true 
  