language: ruby
cache: bundler
rvm:
  - "2.1.1"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
services:
  - postgresql
addons:
  postgresql: "9.4"