default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  database: travis_ci_test

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  